### ISSUE TITLE
WPU Moment

### ISSUE THREAD

**Issue by galihap76** [mizzcode/fundamental-js#1]
Kaya ora asing source code javascript e, sing WPU ya? soale enyong juga ana sih. Dadi kangen awal belajar javascript pas kelas 11 SMK, pas corona esih rame. Terima kasih corona, berkat Anda saya bisa sampai sini.🥺

**Comment by galihap76** [comment]
Histori : <a href="https://github.com/galihap76/repo-projek">repo projek</a>.

**Comment by mizzcode** [comment]
Berantakan struktur folder e jadi keder

**Comment by mizzcode** [comment]
sekalian mengulang basic js biar fundamental e kuat sebelum mencicipi framework e😂

**Comment by mizzcode** [comment]
> Kaya ora asing source code javascript e, sing WPU ya? soale enyong juga ana sih. Dadi kangen awal belajar javascript pas kelas 11 SMK, pas corona esih rame. Terima kasih corona, berkat Anda saya bisa sampai sini.🥺

gg jadi mulai mengenal kue kelas 11 ?

**Comment by mizzcode** [comment]
> Kaya ora asing source code javascript e, sing WPU ya? soale enyong juga ana sih. Dadi kangen awal belajar javascript pas kelas 11 SMK, pas corona esih rame. Terima kasih corona, berkat Anda saya bisa sampai sini.🥺

gg jadi mulai mengenal kue kelas 11 ?

**Comment by galihap76** [comment]
> > Kaya ora asing source code javascript e, sing WPU ya? soale enyong juga ana sih. Dadi kangen awal belajar javascript pas kelas 11 SMK, pas corona esih rame. Terima kasih corona, berkat Anda saya bisa sampai sini.🥺
> 
> gg jadi mulai mengenal kue kelas 11 ?

Iya wkwk perasaan wis tak cerita kena deh.

**Comment by mizzcode** [comment]
> > > Kaya ora asing source code javascript e, sing WPU ya? soale enyong juga ana sih. Dadi kangen awal belajar javascript pas kelas 11 SMK, pas corona esih rame. Terima kasih corona, berkat Anda saya bisa sampai sini.🥺
> > 
> > 
> > gg jadi mulai mengenal kue kelas 11 ?
> 
> Iya wkwk perasaan wis tak cerita kena deh.

yakah:?
trus bisane ora fokus neng js gal? tapi beralih ke php ? alesan ne apa

**Comment by galihap76** [comment]
> > > > Kaya ora asing source code javascript e, sing WPU ya? soale enyong juga ana sih. Dadi kangen awal belajar javascript pas kelas 11 SMK, pas corona esih rame. Terima kasih corona, berkat Anda saya bisa sampai sini.🥺
> > > 
> > > 
> > > gg jadi mulai mengenal kue kelas 11 ?
> > 
> > Iya wkwk perasaan wis tak cerita kena deh.
> 
> yakah:?
> trus bisane ora fokus neng js gal? tapi beralih ke php ? alesan ne apa

Karena mbiyen pas SMP duwe keinginan pengen belajar PHP tapi ora kesampaian soale durung ngerti alur belajare pimen.

Barang sekolah online gara gara corona enyong coba belajar javascript disit terus manjing back end. Makane enyong seneng sing arane pemrograman PHP soale wis ana keinginan suwe.

**Comment by mizzcode** [comment]
owalah... mirip kaya nyong juga sih semoga ngko dwek bisa kerja jadi programmer gal 👍

**Comment by galihap76** [comment]
> owalah... mirip kaya nyong juga sih semoga ngko dwek bisa kerja jadi programmer gal 👍 

Aamiin.
